### ISSUE TITLE
Limit 2600-2700

### ISSUE THREAD

**Issue by Randomine** [votacom/skarbal#2] opened 2020-08-31 18:20 UTC
The program is´nt able to calcutate dates after a certain date in the 27th century.

**Comment by votacom** [comment] 2020-08-31 19:15
Hi @Randomine,
unfortunately I cannot reproduce the issue.
This is what I am getting:

```
>> s 2650-12-15
Gregorian: Thu 12/05/50
Skarbal: Friday, 2650-12-15
>> g 2650-12-15
Gregorian: Sun 12/15/50
Skarbal: Monday, 2650-12-25
```

Could you perhaps retest with the latest update that solves #1? If it still doesn't work, please post the program output.

**Comment by Randomine** [comment] 2020-08-31 20:30
Well you should produce the issue better!
For example type in something with the year 2700, you will see;

>> g 2700-21-12
A parsing error occured. Type `help` to see available commands.
Gregorian: Mon 08/31/20
Skarbal: Sunday, 2020-09-10

If i try a year like 7000 past Christ the program closes itself.

Gute Nacht, ich liebe meinen IT-Support, du bist die Beste!
bussi





Am Mo., 31. Aug. 2020 um 21:16 Uhr schrieb Manuel Bichler <
notifications@github.com>:

**Comment by votacom** [comment] 2020-08-31 22:33
Hi,
2700-21-12 is not a valid date. There is no 21st month. I agree that "a parsing error occured" is not very helpful (and has a typo!).
I'll look into the issues.

**Comment by votacom** [comment] 2020-08-31 22:47
Hi,
this problem should be solved in the current state of the master branch.
Please retest on your end. I will close this issue for now.

**Closed as completed by votacom** 2020-08-31 22:47 UTC
Labels: bug
